### ISSUE TITLE
Easy adding mode

### ISSUE THREAD

**Issue by HolgerJeromin** [simonpoole/OpeningHoursFragment#13]
It is cool, that vespucci can edit all complex opening hours. 
But entering an simple string is really cumbersome. 

It would be great if there would be a gui like the one from streetcomplete for quick entering strings like:
Mo-Fr 08:00-19:00;Sa 09:00—14:00;Su, PH off

**Comment by simonpoole** [comment]
Just create a corresponding template and use that (modifying the times slightly if necessary). For example the existing weekdays template.

**Comment by simonpoole** [comment]
See also https://github.com/simonpoole/OpeningHoursFragment

**Comment by simonpoole** [comment]
BTW Mo-Fr 08:00-19:00;Sa 09:00—14:00;Su, PH off is not a valid OH value, it should be (if that is what you ment):

Mo-Fr 08:00-19:00;Sa 09:00—14:00; PH,Su off

(See http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification weekday_selector)

**Comment by simonpoole** [comment]
Further note: this may be a bit of a workflow issue in vespucci itself, since we are assuming that you add the OH tag via a preset (or reapplying a preset) see: https://github.com/MarcusWolschon/osmeditor4android/issues/586

**Comment by HolgerJeromin** [comment]
OK, templates are nice. Thanks for the hint. 

Perhaps with using them my problem is that my phone is too small (5 inch) or my finger not precise enough to change a hour/minute to the correct value on the first try. I need mostly three attempts on every change. 
That is why the the streetcomplete gui with the native time input is much easier to use.

**Comment by HolgerJeromin** [comment]
I have never seen a requirement to have the PH before a day... 
cc @ypid

**Comment by simonpoole** [comment]
The default time increment is 15 minutes which in my experience should work in most cases, alternatives would be to allow a number picker as an input method or add an additional larger increment on the bars.

**Comment by ypid** [comment]
> Mo-Fr 08:00-19:00;Sa 09:00—14:00; PH,Su off

Good point. Thanks. According to the definition of [weekday_selector](http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#weekday_selector) @simonpoole is correct. I would say this is a bug in the spec. `Su,PH off` is [quite common](https://taginfo.openstreetmap.org/search?q=opening_hours%3DSu%2CPH). @simonpoole What do you think?

**Comment by HolgerJeromin** [comment]
What about two time wheels (keeping 15/5/1 minutes increments for selecting speed) in the time row like this one
http://blog.teamtreehouse.com/wp-content/uploads/2012/12/time.png
Uses perhaps too much vertical space...

**Comment by simonpoole** [comment]
@ypid IMHO even if this specific variant is easy to handle I still wouldn't make it "official" except if holidays are treated completely the same as weekdays which may have a lot of undesired consequences.

**Comment by ypid** [comment]
OK, valid point. I had similar issues already in opening_hours.js. On the other hand `Mo-Fr 08:00-19:00; Sa 09:00-14:00; Su,PH off` looks like the (for humans [😉](https://github.com/simonpoole/OpeningHoursFragment/issues/14#issuecomment-316836300)) logical order (first all weekdays are handled, and the last rule conveniently also sets `PH` to closed). I guess this calls for a proper proposal once more. Added to my todo.

Related to: https://github.com/simonpoole/OpeningHoursParser/issues/6#issuecomment-229504126

**Comment by simonpoole** [comment]
https://github.com/simonpoole/OpeningHoursFragment/commit/089b56df23f1adaf75b31d124828ee1d471a5f37 adds a number picker as alternative method to edit time ranges
![screenshot_20170729-232305](https://user-images.githubusercontent.com/1011860/28748426-0ad61bd4-74b8-11e7-84fa-7c3c66ddbfd5.png)

**Comment by simonpoole** [comment]
No further comments, closing.
