### ISSUE TITLE
Selecting empty modifier crashes Vespucci

### ISSUE THREAD

**Issue by matkoniecz** [simonpoole/OpeningHoursFragment#43]
To reproduce in Vespucci:

add empty opening hours
Select Weekdays template
Switch modifier for public holidays to empty one

**Comment by simonpoole** [comment]
The crash is due to an empty string not bing mapped to unknown as it should be according to https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#section:rule_modifier (and likely the empty selection should not be offered at all).

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/OpeningHoursFragment/commit/1eb4c13bfb51a0cf7ff5bb7f93c4d6e749b5d89c and https://github.com/simonpoole/OpeningHoursParser/commit/2c3cf26c6e671bd10eff223d4983af7953191658
