### ISSUE TITLE
“Save to file” dialog in “Manage templates” could be improved

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/OpeningHoursFragment#53]
## Behaviour/Symptoms
When I used the “Save to file” command in “Manage templates” the first time(s), I did not see the input field for a file name at all – I thought it is only possible to choose a folder to save to. I only saw the **SAVE** button at the bottom right (“SPEICH.“ on my german system) and directly pressed it, because the input field is nearly invisible as long as you don't tap on it (and it gets focus with a cursor) – then it also gets a slightly thicker line, but it's still not very clearly visible ... it's a white field on a white background with a thin line.

Here are 2 screenshots (scaled down):

![“Save to file” dialog 01 270px](https://user-images.githubusercontent.com/48966999/140670111-5de27c3c-aaa9-49f0-8b4d-20e4ef447c5e.png)    ![“Save to file” dialog 02 (with focus) 270px](https://user-images.githubusercontent.com/48966999/140670119-bb225857-bd07-4cc4-94c6-21d0b54bdfb4.png)

And if you press the save button without entering a file name you get a file with the name “(invalid)”. And if such a file already exist, the result is “(invalid) (1)“. 

When I used the command the first time(s), this was some kind of confusing (although the content of the file is completely OK – and not invalid ...). It took some time until I detected the input field ... and I think I'm not a very unexperienced user ...

## Vespucci /Android Version/Device

- Vespucci v16.1.0
- Android v9.1.0
- Honor 7x

## Expected Behaviour

If you really don't enter a file name and press the SAVE button, a better and descriptive file name would be nice ... perhaps something like “Opening hours template database file.txt”. Or a warning should appear that you have to enter a file name.

##  UI Improvements

- The visibility of the input field could be much better – perhaps not a white field on a white background (but I don't know if you can change a lot here, perhaps it depends on the Android version?).
- And (or at least) the input field should get focus directly after using the “Save to file” command (to have a cursor and a thicker line).

**Comment by simonpoole** [comment]
The SAF file picker is an activity provided by the system (exact visual appearance depends on the Android version) and can't be easily replaced. Further we don't have any control over it's internal workings so can't determine what gets focus when. Yes that kind of sucks.

We should however catch an empty URL being returned so leaving open for now.

**Comment by jajajaneeneenee** [comment]
How bad that you don't have more control over the file picker. It's also not possible to display a (grey) hint text in the input field (something like "Enter filename here")?

Or perhaps you should prefill this input field with a default name (like “Opening hours template database file.txt”), it this is possible. It would save you the hassle of thinking up or typing a filename (or you could change it if you don't like it) I don't know if this would be possible ... perhaps not ...

But in any case, an empty input field should be catched, yes!
